### ISSUE TITLE
TP terminé

### ISSUE THREAD

**Issue by julesdruguet** [PolytechLyon/2019-isi3-graph-degefa_druguet#7]
Bonjour,

Je créé cette issue pour vous informer que notre commit final a été effectué ce matin et que le TP est terminé.

Bonne relecture ;)

@dselome & @julesdruguet

**Comment by Slashgear** [comment]
- 👍 Rapport

- Trouvez ce qui me choque dans cette ligne 

https://github.com/PolytechLyon/2019-isi3-graph-degefa_druguet/blob/abdf1a3731c685ab07219f6887fac673ad7fba1f/src/main/java/graph/GraphIterator.java#L35

C'est quoi la différence entre un Set et une List en Java, pourquoi ici nous devrions utiliser un Set ?

https://github.com/PolytechLyon/2019-isi3-graph-degefa_druguet/blob/abdf1a3731c685ab07219f6887fac673ad7fba1f/src/main/java/graph/Graph.java#L42

**Comment by julesdruguet** [comment]
> * Trouvez ce qui me choque dans cette ligne
> 
> [2019-isi3-graph-degefa_druguet/src/main/java/graph/GraphIterator.java](https://github.com/PolytechLyon/2019-isi3-graph-degefa_druguet/blob/abdf1a3731c685ab07219f6887fac673ad7fba1f/src/main/java/graph/GraphIterator.java#L35)
> 
> Line 35 in [abdf1a3](/PolytechLyon/2019-isi3-graph-degefa_druguet/commit/abdf1a3731c685ab07219f6887fac673ad7fba1f)
> 
>  public void addNodeToTreat(Node nodeToTreat) { 

Le type d'objet passé en argument n'a pas à être indiqué dans le nom de la méthode ?
Il faudrait avoir quelque chose comme :
`public void addToTreat(Node node) { `
ou
`public void addToList(Node node) {`



> [2019-isi3-graph-degefa_druguet/src/main/java/graph/Graph.java](https://github.com/PolytechLyon/2019-isi3-graph-degefa_druguet/blob/abdf1a3731c685ab07219f6887fac673ad7fba1f/src/main/java/graph/Graph.java#L42)
> 
> Line 42 in [abdf1a3](/PolytechLyon/2019-isi3-graph-degefa_druguet/commit/abdf1a3731c685ab07219f6887fac673ad7fba1f)
> 
>  public List<Node> getAllNodes() {

Un Set n'est pas ordonné et ne peut pas contenir de doublons, or ici ce qui est pertinent c'est simplement de récupérer les noeuds du graphe => un ordonnancement ne se justifie pas sur cette méthode.

**Comment by Slashgear** [comment]
Pour le premier point: 
Dans une classe abstraite, les méthodes que l'on souhaite surcharger dans les classes enfants, on peut les indiquer comme ?

**Comment by dselome** [comment]
On conserve une méthode non abstraite lorsqu'il existe une fonctionnalité commune pour toutes ses classes enfants. Ici notre méthode change en fonction des sous-classes donc on doit la déclarer comme abstraite.
> public abstract void addNodeToTreat(Node node);

**Comment by Slashgear** [comment]
On le fait ? :)

**Comment by julesdruguet** [comment]
Changements effectués sur la master !
